language: java

jdk:
    - oraclejdk7

sudo: false

cache:
  directories:
  - $HOME/protobuf

before_install:
    - bash travis-install-protobuf.sh
    - export PATH=$HOME/protobuf/bin:$PATH
    - export MAVEN_OPTS=-Dprotoc=$HOME/protobuf/bin/protoc $MAVEN_OPTS
    - echo path=$PATH
    - echo maven_opts=$MAVEN_OPTS
