#
# Before installing, we need to install protoc 2.4.1 and then checkout and build the aloha-proto project
# in case the current aloha version is using a snapshot.  If it's not using a snapshot, no harm, no foul.

language: java
jdk:
    - oraclejdk7
before_install:
    - wget https://protobuf.googlecode.com/files/protobuf-2.4.1.tar.gz
    - tar -xzvf protobuf-2.4.1.tar.gz
    - cd protobuf-2.4.1 && ./configure --prefix=/usr && make && sudo make install
    - cd -
