language: java

jdk:
    - oraclejdk7

sudo: false

cache:
  directories:
  - $HOME/protobuf

before_install:
    - bash travis-install-protobuf.sh

install: mvn install -Dmaven.test.skip=true -DskipTests=true -Dmaven.javadoc.skip=true

script: mvn test -Dprotoc=$HOME/protobuf/bin/protoc
