language: java

jdk:
    - oraclejdk7

sudo: false

cache:
  directories:
  - $HOME/protobuf

before_install:
    - bash travis-install-protobuf.sh
    - echo path=$PATH
    - echo maven_opts=$MAVEN_OPTS
